spring.application.name=alumniportal

spring.datasource.url=jdbc:postgresql://localhost:5432/alumniportal
spring.datasource.username=postgres
spring.datasource.password=xxxxx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=QUDbpum4xbnc1BKq6iYhfhwUvu5ECERMMyKV6LIORO4=
app.jwt.expiration-ms=3600000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB